name: Java CI Workflow

on:
  push:
    branches:
      - Feature
  pull_request:
    branches:
      - Feature

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Use 'zulu' or 'adopt' if preferred
          java-version: '17'
          cache: 'maven'  # Caches dependencies for faster builds

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn test

      - name: Upload Test Results (Optional)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports/

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v3
        with:
          name: application-jar
          path: target/*.jar
